# Generated by Django 3.2.8 on 2022-02-25 13:51

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_auto_20220225_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite',
            new_name='add_favourite',
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 13, 51, 54, 711929, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
