# Generated by Django 3.2.8 on 2022-02-25 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220225_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 14, 1, 52, 841751, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
