# Generated by Django 3.2.8 on 2022-02-26 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220226_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='ProductColorSize',
            new_name='productColorSize',
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 26, 12, 20, 31, 767963, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
