# Generated by Django 3.2.8 on 2022-02-27 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20220227_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterModelOptions(
            name='orderfeedback',
            options={'verbose_name': 'OrderFeedback', 'verbose_name_plural': 'OrderFeedback'},
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'ProductGallery', 'verbose_name_plural': 'ProductGallery'},
        ),
        migrations.AlterField(
            model_name='orderfeedback',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 10, 16, 15, 217527, tzinfo=utc), verbose_name='Data'),
        ),
    ]
