# Generated by Django 3.2.8 on 2022-02-28 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20220227_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfeedback',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 12, 43, 34, 708964, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='product',
            name='body',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='product'),
        ),
    ]
