# Generated by Django 3.2.8 on 2022-03-12 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20220304_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfeedback',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 8, 53, 25, 822816, tzinfo=utc), verbose_name='Data'),
        ),
    ]
