# Generated by Django 3.2.8 on 2022-03-12 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_orderfeedback_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='number',
            field=models.TextField(default=0, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='orderfeedback',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 8, 55, 7, 310252, tzinfo=utc), verbose_name='Data'),
        ),
    ]
