# Generated by Django 3.2.8 on 2022-03-12 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20220312_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfeedback',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 8, 58, 14, 115980, tzinfo=utc), verbose_name='Data'),
        ),
    ]
